### ISSUE TITLE
Email template for notifications

### ISSUE THREAD

**Issue by deepakkumarnd** [openvitae-tech/blackboard-lms#100]
**Scenario 1**

Manager assigned  a course to a learner. An email notification has to be sent with following message.

"{Manager} has assigned course {Course Name} to you"

**Scenario 2**

User started  a course that the manager has assigned. An email notification has to be sent with following message.

"{UserName} has started with the course {CourseName} assigned by you"

The course name should be a link which takes the user to the course details page.

**Comment by Vaisakh-mv** [comment]
![Screenshot 2024-10-23 at 10 09 33 PM](https://github.com/user-attachments/assets/68250f8e-e097-4f4c-a3e7-5516d0685be3)

email notification has been completed, Please review
