### ISSUE TITLE
Add `pry-byebug` gem

### ISSUE THREAD

**Issue by paulsojan** [openvitae-tech/blackboard-lms#113]
https://github.com/deivid-rodriguez/pry-byebug

Adds step-by-step debugging and stack navigation capabilities to pry using byebug. Gem supports both syntax - `pry` and `byebug`.

**Comment by deepakkumarnd** [comment]
@paulsojan Is there any advantage over the current debugger gem that we use ?

**Comment by paulsojan** [comment]
@deepakkumarnd Just tried the `debug` gem. Since Rails 7 replaced `byebug` with `debug` gem, we can continue using it as it provides the same functionalities. So closing the issue.
