### ISSUE TITLE
Spacing issue in course page

### ISSUE THREAD

**Issue by deepakkumarnd** [openvitae-tech/blackboard-lms#131]
![Screenshot 2024-10-22 at 3 23 40 PM](https://github.com/user-attachments/assets/3c2beaed-0e6e-463e-8b5f-f612a0866db3)

**Comment by sadrisya** [comment]
![Screenshot 2024-10-29 at 3 56 03 PM (2)](https://github.com/user-attachments/assets/402d0997-5c26-4df0-95cb-592241e64f09)
Issue is resolved
