### ISSUE TITLE
Suggestions on course page

### ISSUE THREAD

**Issue by paulsojan** [openvitae-tech/blackboard-lms#141]
https://paulsojan.neetorecord.com/watch/34856fc7-abf7-4b01-9657-02e85fd38501

- [ ] Show only modules with lessons 
<img width="1257" alt="Screenshot 2024-10-23 at 9 37 28 PM" src="https://github.com/user-attachments/assets/7f8dec7f-c7f8-4615-840b-9702a97fcbbb">

- [ ] #183
- [ ] #184
- [x] Ability to edit lessons from the module show page. 

cc: @deepakkumarnd

**Comment by deepakkumarnd** [comment]
Ability to edit lessons from module show page is done.
