### ISSUE TITLE
Admin views are not available in mobile. Show a message .

### ISSUE THREAD

**Issue by deepakkumarnd** [openvitae-tech/blackboard-lms#152]
Admin views are not available in mobile at present. When an admin user checks from a mobile show a message saying that to use a desktop brower for admin pages.

**Comment by Vaisakh-mv** [comment]
![Screenshot 2024-11-01 at 11 03 48 AM](https://github.com/user-attachments/assets/0ce10e02-8ba4-41a3-ad18-b45245f61ef0)

**Comment by sadrisya** [comment]
Working on this
