### ISSUE TITLE
Team banner looks bad in team page

### ISSUE THREAD

**Issue by deepakkumarnd** [openvitae-tech/blackboard-lms#174]
<img width="267" alt="Screenshot 2024-10-25 at 4 13 40 PM" src="https://github.com/user-attachments/assets/1c34c6c2-b1ab-4c66-adc1-2f0f4de6cb46">

Team banner looks bad in team page

**Comment by Vaisakh-mv** [comment]
team banner updated the UI Page. Please review 
![Screenshot 2024-11-18 at 6 08 05 PM](https://github.com/user-attachments/assets/a1818349-9b50-4aef-b6cc-52232b054e28)
