### ISSUE TITLE
Banner not looking good in user setting page

### ISSUE THREAD

**Issue by deepakkumarnd** [openvitae-tech/blackboard-lms#175]
<img width="565" alt="Screenshot 2024-10-25 at 10 02 21 PM" src="https://github.com/user-attachments/assets/3aacf42f-4863-41b5-8da0-e4a598a52f4e">

Banner not looking good in user setting page
![Screenshot 2024-10-30 at 5 35 18 PM](https://github.com/user-attachments/assets/62a25eae-eda7-45ee-a62f-46f957ef52dd)

**Comment by Vaisakh-mv** [comment]
![Screenshot 2024-11-05 at 11 14 48 PM](https://github.com/user-attachments/assets/402c3c69-0fe8-4cff-86c4-e53371867d38)

banner Updated

**Comment by Vaisakh-mv** [comment]
Updated User setting page, including the banner section on web & mobile - please review 

![Screenshot 2024-11-18 at 5 11 50 PM](https://github.com/user-attachments/assets/e1233d8f-6b1f-447c-9e67-d5fb05d452ed)
