### ISSUE TITLE
Use a placeholder image for logo and banners

### ISSUE THREAD

**Issue by deepakkumarnd** [openvitae-tech/blackboard-lms#274]
1. The placeholder should be a grayscale image, 
2. The image should be less than 1 MB
3. The image should have mention of resolutions.
4. The placeholder should be shown by default when user haven't set those images.

**Comment by Vaisakh-mv** [comment]
![Banner_mobile](https://github.com/user-attachments/assets/38d8bd09-8e8b-4040-8447-e53b9afd2c0e)
![Banner_web](https://github.com/user-attachments/assets/bb7377d5-8a0a-4869-9245-d92c2221cc60)
![Logo_placeholder_80](https://github.com/user-attachments/assets/a027afa9-ebc8-44d9-873d-45e3de440880)

Placeholder for Banner & Logo, Design completed
