### ISSUE TITLE
Add favicon 

### ISSUE THREAD

**Issue by deepakkumarnd** [openvitae-tech/blackboard-lms#340]
Add favicon logo

**Comment by Vaisakh-mv** [comment]
![Instruo_logo_blue_round](https://github.com/user-attachments/assets/71723e19-d486-4638-8798-966005589752)
![Instruo_logo_blue_round@](https://github.com/user-attachments/assets/4363225c-bbb0-481b-a5ab-958260416701)

Favicon updated to 16x16 PNG and SVG formats.
