### ISSUE TITLE
 Improve User Settings Page Design and Structure

### ISSUE THREAD

**Issue by sadrisya** [openvitae-tech/blackboard-lms#364]
The current design of the User Settings page can be enhanced for better user experience and content clarity. The following issues have been identified:

1.Redundant Headings:
   The page includes two headings: "User Settings" and "My Profile". This redundancy can confuse users.

2.Header Content:
    The user's name is included in the main content header. Instead, it could be better positioned within the body or as a     replacement for the "My Profile" heading.

3.Body Content Structure:
      The body content currently includes personal information like email and phone number but lacks clarity. It needs restructuring for improved readability and hierarchy.

![Screenshot 2024-12-03 at 2 15 38 PM](https://github.com/user-attachments/assets/a721c776-52b5-47ec-a9ce-48be61f47067)
![Screenshot 2024-12-03 at 2 20 38 PM](https://github.com/user-attachments/assets/8c6c1a00-4175-4087-a78c-3ade0c6e13c2)

**Comment by Vaisakh-mv** [comment]
![Screenshot 2024-12-06 at 12 05 44 PM](https://github.com/user-attachments/assets/e83bd006-d4a9-49f1-85e2-7d0a277fa330)
![Screenshot 2024-12-06 at 12 06 17 PM](https://github.com/user-attachments/assets/6ee3d847-e9df-454c-b785-6a86229eb451)
Design updated in - Design handoff
