### ISSUE TITLE
create a beta logo and use beta logo till release

### ISSUE THREAD

**Issue by deepakkumarnd** [openvitae-tech/blackboard-lms#400]

**Comment by Vaisakh-mv** [comment]
![instruo_beta_logo_mobile](https://github.com/user-attachments/assets/a8be2d8c-dda6-4c4a-be62-f33bdbe7f42f)
![instruo_beta_logo](https://github.com/user-attachments/assets/076609fa-cf2d-4442-a622-631119437e7c)

Beta logo updated
