### ISSUE TITLE
Implement notifications

### ISSUE THREAD

**Issue by deepakkumarnd** [openvitae-tech/blackboard-lms#5]

**Comment by Vaisakh-mv** [comment]
![Screenshot 2024-11-18 at 4 12 28 PM](https://github.com/user-attachments/assets/8bb84080-f3be-42bf-a284-dd0e0f69b722)

# Notification UI Pages

**Comment by Vaisakh-mv** [comment]
https://www.figma.com/design/CvwQsUQ5LH19pB2Nxup3Kr/VD_skill.app?node-id=4913-34806&t=6zlkkJuXmA5kZN0v-1

**Comment by deepakkumarnd** [comment]
@Vaisakh-mv screenshot please, figma is not visible to all
