### ISSUE TITLE
Show more show less on course description

### ISSUE THREAD

**Issue by deepakkumarnd** [openvitae-tech/blackboard-lms#51]
<img width="393" alt="Screenshot 2024-10-04 at 11 05 09 AM" src="https://github.com/user-attachments/assets/a9ef2562-4194-46c5-9880-e3fd23f20791">

The description is not visible in course page, the course description should be made visible when clicking on show more. On clicking show less the description should shrink

**Comment by sadrisya** [comment]
partially done small style issue persist on the description box
fixes #59
