### ISSUE TITLE
Notice design needs improvement.

### ISSUE THREAD

**Issue by deepakkumarnd** [openvitae-tech/blackboard-lms#88]
Sometimes notice doesn't look nice with the yellow color. The white and yellow combination doesn't seem to work well. The close icon is not visible with light background.

![Screenshot 2024-10-17 at 10 08 22 AM](https://github.com/user-attachments/assets/df9eaaf4-1b96-4f88-a2be-6643022cf450)

**Development**
The close should happen automatically after 3 seconds with a nice fade out effect.

**Comment by Vaisakh-mv** [comment]
![Screenshot 2024-10-17 at 5 29 46 PM](https://github.com/user-attachments/assets/e44b66b0-bbb1-4ae0-8b46-311e42a5e806)

**Comment by Vaisakh-mv** [comment]
Text & icon color change to black

**Comment by sadrisya** [comment]
fixes  #107
