### ISSUE TITLE
Remove itaic on page titles

### ISSUE THREAD

**Issue by deepakkumarnd** [openvitae-tech/blackboard-lms#90]
![Screenshot 2024-10-17 at 11 13 51 AM (2)](https://github.com/user-attachments/assets/f0f7a9d0-d672-43e7-bde1-53821bc5e838)

**Comment by Vaisakh-mv** [comment]
![Screenshot 2024-10-17 at 5 10 50 PM](https://github.com/user-attachments/assets/a97b890b-9f00-474a-ac90-8aec936290cd)
Font changes have been updated
