### ISSUE TITLE
Brocken styles in dashboard

### ISSUE THREAD

**Issue by deepakkumarnd** [openvitae-tech/blackboard-lms#97]
Blue outline on the select box

![Screenshot 2024-10-17 at 4 03 34 PM](https://github.com/user-attachments/assets/3dfc614e-6259-4dcd-b949-5deb3a73b061)

Alignment issues between graphs
![Screenshot 2024-10-17 at 12 29 17 PM](https://github.com/user-attachments/assets/f0d0441f-9a6b-4e0d-b165-5412ea9b7f16)

Ideally sections where two graphs are present should follow two column. Default width should be whatever spaces available on the screen with a max width on the whole main content. So that the graphs won't grow too much and won't look bad.

**Comment by sadrisya** [comment]
fixes #109
